on:
  push:
    branches:
      - main

permissions: {}

jobs:
  scorecard:
    name: Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: UpCloudLtd/workflows/.github/workflows/openssf-scorecard.yml@df484f518667d7ccdf0dfbca4fffb5d10d1ba5b7 # main
