on:
  push:
    branches:
      - main

permissions: {}

jobs:
  scorecard:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: scop/workflows/.github/workflows/openssf-scorecard.yaml@main
    with:
      publish-results: true
